"""
LinkedIn Posting Automation
---------------------------
Runs every ~15 min via GitHub Actions. Pulls the next pending row from a Google
Sheet, generates a draft via Anthropic Claude, posts it to a Slack channel for
review, polls the thread for `approve` / `reject` / `regenerate: <feedback>`,
and on approval publishes to LinkedIn and writes status back to the sheet.

State (which SNos are mid-flight, member ID cache, last-drafted-date) lives in
a hidden `_state` tab of the same Google Sheet, as a key/value store.

This script is intentionally idempotent. Running it twice in a minute produces
no duplicate work.

Required env vars (loaded from GitHub Actions secrets):
  GOOGLE_SERVICE_ACCOUNT_JSON  - the entire service account JSON, as a string
  SHEET_ID                     - the Google Sheet ID
  ANTHROPIC_API_KEY            - sk-ant-...
  SLACK_BOT_TOKEN              - xoxb-...
  SLACK_CHANNEL_ID             - the channel ID (e.g. C0B1BRD5PDG), NOT the name
  LINKEDIN_TOKEN               - your LinkedIn access token (60-day rotation)

Optional:
  TZ                           - IANA timezone for daily-trigger logic. Default: Asia/Kolkata
  DAILY_DRAFT_HOUR             - hour (0-23) in TZ to draft at. Default: 10
  ANTHROPIC_MODEL              - default: claude-sonnet-4-6
  DRY_RUN                      - if "1", skip the actual LinkedIn POST (still does everything else)
"""

from __future__ import annotations

import json
import logging
import os
import re
import sys
import time
from dataclasses import dataclass, field
from datetime import datetime, timedelta
from typing import Any, Optional
from zoneinfo import ZoneInfo

import gspread
import requests
from anthropic import Anthropic
from google.oauth2.service_account import Credentials
from slack_sdk import WebClient
from slack_sdk.errors import SlackApiError

# --------------------------------------------------------------------------- #
# Configuration                                                               #
# --------------------------------------------------------------------------- #

LOG = logging.getLogger("linkedin_automation")
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)

SHEETS_SCOPES = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.readonly",
]

STATE_TAB_NAME = "_state"

# Anthropic model - using the default Sonnet model
ANTHROPIC_MODEL = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")

LINKEDIN_API_BASE = "https://api.linkedin.com"
LINKEDIN_USERINFO = f"{LINKEDIN_API_BASE}/v2/userinfo"
LINKEDIN_UGC_POSTS = f"{LINKEDIN_API_BASE}/v2/ugcPosts"

# These are the canonical column names we look for in the sheet (case-insensitive
# match, lenient to whitespace and parenthesized hints).
CANONICAL_COLUMNS = {
    "sno": ["sno", "sno.", "s.no", "serial", "#"],
    "date": ["date"],
    "topic": ["topic"],
    "angle": ["angle"],
    "key_points": ["key points", "keypoints", "points"],
    "voice": ["voice", "tone"],
    "hook_style": ["hook style", "hook"],
    "link": ["link", "url"],
    "cta": ["cta", "call to action"],
    "status": ["status"],
    "post_url": ["post url", "posturl", "linkedin url", "published"],
    "reach_score": ["reach score", "reachscore"],
    "notes": ["notes"],
    "generated_by": ["generated by"],
}

# AI-trend fallback themes — rotated when the queue is empty. The prompt is
# given to Claude to produce a thoughtful post within one of these themes.
TREND_THEMES = [
    "The gap between AI demos and AI products in production",
    "Why most teams reach for fine-tuning when they actually need RAG",
    "Agent evaluation as the unsolved bottleneck",
    "The quiet rise of small, specialized models",
    "Prompt engineering vs. context engineering",
    "What 'human in the loop' actually requires to work at scale",
    "How AI changes the unit economics of customer support",
    "Why retrieval quality dominates model quality for most use cases",
    "The shift from chatbots to agents that take actions",
    "When to build vs. buy an AI feature in 2026",
]


# --------------------------------------------------------------------------- #
# Helpers                                                                     #
# --------------------------------------------------------------------------- #


def env(name: str, default: Optional[str] = None, required: bool = False) -> str:
    val = os.environ.get(name, default)
    if required and not val:
        LOG.error("Missing required env var: %s", name)
        sys.exit(1)
    return val or ""


def now_local() -> datetime:
    tz_name = env("TZ", "Asia/Kolkata")
    return datetime.now(ZoneInfo(tz_name))


def normalize_header(s: str) -> str:
    # "Generated by (Sagar/Cowork)" -> "generated by"
    s = re.sub(r"\(.*?\)", "", s).strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def map_columns(headers: list[str]) -> dict[str, int]:
    """Map canonical column keys to 0-based indices in the actual header row."""
    norm = [normalize_header(h) for h in headers]
    out: dict[str, int] = {}
    for canonical, aliases in CANONICAL_COLUMNS.items():
        for alias in aliases:
            if alias in norm:
                out[canonical] = norm.index(alias)
                break
    return out


# --------------------------------------------------------------------------- #
# Google Sheets layer                                                         #
# --------------------------------------------------------------------------- #


@dataclass
class SheetClient:
    sheet_id: str
    gc: gspread.Client
    sh: gspread.Spreadsheet
    queue_ws: gspread.Worksheet
    state_ws: gspread.Worksheet
    col_idx: dict[str, int]

    @classmethod
    def connect(cls, sheet_id: str, sa_json: str) -> "SheetClient":
        creds_info = json.loads(sa_json)
        creds = Credentials.from_service_account_info(creds_info, scopes=SHEETS_SCOPES)
        gc = gspread.authorize(creds)
        sh = gc.open_by_key(sheet_id)
        queue_ws = sh.sheet1  # first tab = queue
        # Ensure state tab exists
        try:
            state_ws = sh.worksheet(STATE_TAB_NAME)
        except gspread.WorksheetNotFound:
            LOG.info("Creating %s tab", STATE_TAB_NAME)
            state_ws = sh.add_worksheet(title=STATE_TAB_NAME, rows=200, cols=2)
            state_ws.update("A1:B1", [["key", "value"]])

        headers = queue_ws.row_values(1)
        col_idx = map_columns(headers)
        LOG.info("Mapped queue columns: %s", col_idx)
        return cls(sheet_id, gc, sh, queue_ws, state_ws, col_idx)

    # --- queue tab ---

    def fetch_pending_rows(self) -> list[dict[str, Any]]:
        """Return all rows where Status is empty or 'pending' (case-insensitive)."""
        rows = self.queue_ws.get_all_values()
        if len(rows) < 2:
            return []
        out = []
        status_col = self.col_idx.get("status")
        for i, row in enumerate(rows[1:], start=2):  # row 1 is headers; sheet rows 1-indexed
            row = row + [""] * (max(self.col_idx.values(), default=0) + 1 - len(row))
            status = row[status_col].strip().lower() if status_col is not None else ""
            if status in ("", "pending"):
                out.append({
                    "row_number": i,
                    "raw": row,
                    "sno": self._cell(row, "sno"),
                    "date": self._cell(row, "date"),
                    "topic": self._cell(row, "topic"),
                    "angle": self._cell(row, "angle"),
                    "key_points": self._cell(row, "key_points"),
                    "voice": self._cell(row, "voice"),
                    "hook_style": self._cell(row, "hook_style"),
                    "link": self._cell(row, "link"),
                    "cta": self._cell(row, "cta"),
                    "status": self._cell(row, "status"),
                    "generated_by": self._cell(row, "generated_by"),
                })
        return out

    def _cell(self, row: list[str], key: str) -> str:
        idx = self.col_idx.get(key)
        if idx is None or idx >= len(row):
            return ""
        return str(row[idx]).strip()

    def update_row(self, row_number: int, updates: dict[str, str]):
        """Update specific columns on a given sheet row."""
        for key, value in updates.items():
            idx = self.col_idx.get(key)
            if idx is None:
                LOG.warning("No column mapped for '%s', skipping write", key)
                continue
            col_letter = gspread.utils.rowcol_to_a1(1, idx + 1).rstrip("1")
            cell = f"{col_letter}{row_number}"
            self.queue_ws.update(cell, [[value]])
            LOG.info("Wrote %s=%r to %s", key, value[:60], cell)

    def append_auto_row(self, sno: str, topic: str, voice: str, status: str = "pending"):
        """Append an auto-generated row to the queue. Used for AI-trend fallback."""
        # Build a row in the order of self.queue_ws header columns
        headers = self.queue_ws.row_values(1)
        new_row = [""] * len(headers)
        for key, value in [
            ("sno", sno),
            ("date", now_local().strftime("%Y-%m-%d")),
            ("topic", topic),
            ("voice", voice),
            ("status", status),
            ("generated_by", "Cowork"),
        ]:
            idx = self.col_idx.get(key)
            if idx is not None and idx < len(new_row):
                new_row[idx] = value
        self.queue_ws.append_row(new_row, value_input_option="USER_ENTERED")
        # Find the row number we just appended
        all_rows = self.queue_ws.get_all_values()
        return len(all_rows)

    # --- state tab (key/value) ---

    def state_get(self, key: str, default: Any = None) -> Any:
        rows = self.state_ws.get_all_values()
        for r in rows[1:]:
            if r and r[0] == key:
                if len(r) >= 2 and r[1]:
                    try:
                        return json.loads(r[1])
                    except json.JSONDecodeError:
                        return r[1]
                return default
        return default

    def state_set(self, key: str, value: Any):
        rows = self.state_ws.get_all_values()
        serialized = json.dumps(value) if not isinstance(value, str) else value
        for i, r in enumerate(rows[1:], start=2):
            if r and r[0] == key:
                self.state_ws.update(f"B{i}", [[serialized]])
                return
        self.state_ws.append_row([key, serialized], value_input_option="RAW")


# --------------------------------------------------------------------------- #
# LinkedIn layer                                                              #
# --------------------------------------------------------------------------- #


def linkedin_get_member_id(token: str) -> str:
    r = requests.get(
        LINKEDIN_USERINFO,
        headers={"Authorization": f"Bearer {token}"},
        timeout=15,
    )
    if r.status_code == 401:
        raise RuntimeError("LinkedIn token rejected (401). Token expired or invalid.")
    r.raise_for_status()
    data = r.json()
    sub = data.get("sub")
    if not sub:
        raise RuntimeError(f"LinkedIn userinfo response missing 'sub': {data}")
    return sub


def linkedin_publish_post(token: str, member_id: str, text: str) -> str:
    """Publish a text post. Returns the public post URL."""
    body = {
        "author": f"urn:li:person:{member_id}",
        "lifecycleState": "PUBLISHED",
        "specificContent": {
            "com.linkedin.ugc.ShareContent": {
                "shareCommentary": {"text": text},
                "shareMediaCategory": "NONE",
            }
        },
        "visibility": {"com.linkedin.ugc.MemberNetworkVisibility": "PUBLIC"},
    }
    r = requests.post(
        LINKEDIN_UGC_POSTS,
        headers={
            "Authorization": f"Bearer {token}",
            "X-Restli-Protocol-Version": "2.0.0",
            "Content-Type": "application/json",
        },
        data=json.dumps(body),
        timeout=20,
    )
    if r.status_code >= 400:
        raise RuntimeError(f"LinkedIn POST failed [{r.status_code}]: {r.text}")
    urn = r.headers.get("x-restli-id") or r.json().get("id", "")
    # urn looks like urn:li:share:7193... -> URL needs the share id
    share_id = urn.rsplit(":", 1)[-1]
    return f"https://www.linkedin.com/feed/update/urn:li:share:{share_id}/"


# --------------------------------------------------------------------------- #
# Slack layer                                                                 #
# --------------------------------------------------------------------------- #


def slack_post_draft(client: WebClient, channel_id: str, sno: str, draft: str) -> str:
    """Post a new draft to the channel. Returns the thread_ts."""
    text = (
        f":rocket: *Today's LinkedIn Draft (SNo. {sno})*\n\n"
        f"{draft}\n\n"
        f"---\n"
        f"Reply with one of:\n"
        f"• `approve`\n"
        f"• `reject`\n"
        f"• `regenerate: <your feedback>`"
    )
    resp = client.chat_postMessage(channel=channel_id, text=text)
    return resp["ts"]


def slack_repost_in_thread(
    client: WebClient, channel_id: str, thread_ts: str, sno: str, draft: str
) -> None:
    text = (
        f":arrows_counterclockwise: *Regenerated draft (SNo. {sno})*\n\n"
        f"{draft}\n\n"
        f"---\n"
        f"Reply with `approve`, `reject`, or `regenerate: <feedback>`."
    )
    client.chat_postMessage(channel=channel_id, thread_ts=thread_ts, text=text)


def slack_get_latest_user_reply(
    client: WebClient, channel_id: str, thread_ts: str, bot_user_id: str
) -> Optional[str]:
    """Return the text of the latest non-bot reply in the thread, or None."""
    try:
        resp = client.conversations_replies(channel=channel_id, ts=thread_ts, limit=50)
    except SlackApiError as e:
        LOG.warning("Slack thread fetch failed for ts=%s: %s", thread_ts, e.response.get("error"))
        return None
    msgs = resp.get("messages", [])
    LOG.info("Thread %s has %d total messages", thread_ts, len(msgs))
    # Diagnostic: log a compact summary of every message in the thread
    for i, m in enumerate(msgs):
        LOG.info(
            "  msg[%d] user=%s bot_id=%s subtype=%s text_preview=%r",
            i, m.get("user"), m.get("bot_id"), m.get("subtype"),
            (m.get("text") or "")[:60],
        )
    # Reply candidates = anything other than the parent message that wasn't sent
    # by our bot (filter both by user_id and bot_id to be safe)
    user_replies = []
    for m in msgs[1:]:
        if m.get("user") == bot_user_id:
            continue
        if m.get("bot_id"):
            continue
        if not m.get("text"):
            continue
        user_replies.append(m)
    LOG.info("Filtered to %d candidate user replies", len(user_replies))
    if not user_replies:
        return None
    latest_text = user_replies[-1].get("text", "").strip()
    LOG.info("Latest user reply text: %r", latest_text)
    return latest_text


def slack_post_followup(
    client: WebClient, channel_id: str, thread_ts: str, text: str
) -> None:
    client.chat_postMessage(channel=channel_id, thread_ts=thread_ts, text=text)


def slack_get_bot_user_id(client: WebClient) -> str:
    resp = client.auth_test()
    return resp["user_id"]


# --------------------------------------------------------------------------- #
# Anthropic / draft generation                                                #
# --------------------------------------------------------------------------- #

SYSTEM_PROMPT = """You write LinkedIn posts in Sagar's voice — substantive, opinionated, and human. \
You never use AI cliches like "In today's fast-paced world", "Game-changer", "Unlock the power of", \
"Let's dive in", or trailing strings of hashtags. You never use emojis unless explicitly told to. \
You write in plain sentences with line breaks between short paragraphs. Posts are 100-220 words. \
You do not start with "I am excited to" or "Thrilled to share". The opening line is a hook — \
a clear claim, a specific number, a story moment, or a sharp question — never throat-clearing.

If the row provides an Angle, that is the post's central claim. Do not water it down. \
If the row provides Key points, weave all of them in but do not turn the post into a bulleted list. \
If a Voice is specified, match it: thoughtful = considered and slightly contrarian, conversational = \
story-led with a personal moment, punchy = strong opening claim and short paragraphs. \
If a Hook style is specified, open with that pattern.

End the post with the row's CTA if provided; otherwise close with a thought, not a question, unless \
"conversational" voice was requested. If a Link is provided, weave it naturally into a relevant sentence \
near the end - do not just paste it as a footer.

Output only the post text. No preamble, no headers, no markdown."""


@dataclass
class DraftRequest:
    topic: str
    angle: str = ""
    key_points: str = ""
    voice: str = ""
    hook_style: str = ""
    link: str = ""
    cta: str = ""
    feedback: str = ""  # for regenerations


def generate_draft(client: Anthropic, req: DraftRequest) -> str:
    """Call Claude to produce the LinkedIn post text."""
    fields = []
    fields.append(f"Topic: {req.topic}")
    if req.angle:
        fields.append(f"Angle (the central claim): {req.angle}")
    if req.key_points:
        fields.append(f"Key points to weave in:\n{req.key_points}")
    if req.voice:
        fields.append(f"Voice: {req.voice}")
    if req.hook_style:
        fields.append(f"Hook style: {req.hook_style}")
    if req.link:
        fields.append(f"Link to include: {req.link}")
    if req.cta:
        fields.append(f"CTA: {req.cta}")
    if req.feedback:
        fields.append(f"\nUser feedback on the previous draft (address this directly):\n{req.feedback}")

    user_prompt = "Write a LinkedIn post for the following:\n\n" + "\n".join(fields)

    resp = client.messages.create(
        model=ANTHROPIC_MODEL,
        max_tokens=1024,
        system=SYSTEM_PROMPT,
        messages=[{"role": "user", "content": user_prompt}],
    )
    return resp.content[0].text.strip()


def pick_trend_theme(state: SheetClient) -> str:
    """Rotate through TREND_THEMES — pick one we haven't used most recently."""
    last_used = state.state_get("last_trend_theme", "")
    remaining = [t for t in TREND_THEMES if t != last_used]
    pick = remaining[int(time.time()) % len(remaining)]
    state.state_set("last_trend_theme", pick)
    return pick


# --------------------------------------------------------------------------- #
# Core pipeline                                                               #
# --------------------------------------------------------------------------- #


def ensure_member_id(state: SheetClient, token: str) -> str:
    cached = state.state_get("linkedin_member_id")
    if cached:
        return cached
    LOG.info("Fetching LinkedIn member ID for the first time")
    member_id = linkedin_get_member_id(token)
    state.state_set("linkedin_member_id", member_id)
    return member_id


def process_pending_drafts(
    state: SheetClient,
    slack: WebClient,
    anthropic_client: Anthropic,
    channel_id: str,
    bot_user_id: str,
    linkedin_token: str,
    member_id: str,
    dry_run: bool,
):
    """For each draft in 'drafted' state, check Slack thread for user reply."""
    drafts: list[dict] = state.state_get("drafts", [])
    LOG.info("State has %d total drafts", len(drafts))
    for i, d in enumerate(drafts):
        LOG.info("  drafts[%d] sno=%s status=%s thread_ts=%s",
                 i, d.get("sno"), d.get("status"), d.get("thread_ts"))
    if not drafts:
        return

    changed = False
    for d in drafts:
        if d.get("status") != "drafted":
            LOG.info("Skipping SNo. %s (status=%s)", d.get("sno"), d.get("status"))
            continue
        thread_ts = d["thread_ts"]
        LOG.info("Checking SNo. %s (thread_ts=%s) for replies", d.get("sno"), thread_ts)
        reply = slack_get_latest_user_reply(slack, channel_id, thread_ts, bot_user_id)
        if not reply:
            LOG.info("No actionable reply for SNo. %s", d.get("sno"))
            continue
        reply_lc = reply.lower().strip()
        LOG.info("Processing reply for SNo. %s: %r", d.get("sno"), reply_lc[:80])

        if reply_lc.startswith("approve"):
            LOG.info("SNo. %s approved — posting to LinkedIn", d["sno"])
            try:
                if dry_run:
                    post_url = "https://example.com/dry-run-post"
                    LOG.info("[DRY_RUN] Would have posted to LinkedIn")
                else:
                    post_url = linkedin_publish_post(linkedin_token, member_id, d["draft"])
                d["status"] = "posted"
                d["post_url"] = post_url
                d["posted_at"] = now_local().isoformat()
                state.update_row(
                    d["row_number"],
                    {
                        "status": "posted",
                        "post_url": post_url,
                    },
                )
                slack_post_followup(
                    slack, channel_id, thread_ts,
                    f":white_check_mark: Posted to LinkedIn: {post_url}",
                )
                changed = True
            except Exception as e:
                LOG.exception("LinkedIn publish failed for SNo. %s", d["sno"])
                slack_post_followup(
                    slack, channel_id, thread_ts,
                    f":x: LinkedIn post failed: `{e}`. Will retry on next run.",
                )

        elif reply_lc.startswith("reject"):
            LOG.info("SNo. %s rejected", d["sno"])
            d["status"] = "rejected"
            state.update_row(d["row_number"], {"status": "rejected"})
            slack_post_followup(
                slack, channel_id, thread_ts,
                ":no_entry_sign: Marked as rejected. Skipping.",
            )
            changed = True

        elif reply_lc.startswith("regenerate"):
            feedback = reply.split(":", 1)[1].strip() if ":" in reply else ""
            LOG.info("SNo. %s regenerate requested. Feedback: %s", d["sno"], feedback[:80])
            req = DraftRequest(
                topic=d.get("topic", ""),
                angle=d.get("angle", ""),
                key_points=d.get("key_points", ""),
                voice=d.get("voice", ""),
                hook_style=d.get("hook_style", ""),
                link=d.get("link", ""),
                cta=d.get("cta", ""),
                feedback=feedback,
            )
            try:
                new_draft = generate_draft(anthropic_client, req)
                d["draft"] = new_draft
                # Append feedback history to notes
                history = d.get("regen_history", [])
                history.append({"at": now_local().isoformat(), "feedback": feedback})
                d["regen_history"] = history
                slack_repost_in_thread(slack, channel_id, thread_ts, d["sno"], new_draft)
                changed = True
            except Exception as e:
                LOG.exception("Regeneration failed")
                slack_post_followup(
                    slack, channel_id, thread_ts,
                    f":x: Regeneration failed: `{e}`. Try `regenerate: <new feedback>` again.",
                )

        else:
            # Unrecognized reply — do nothing, but only nudge once
            if not d.get("nudged"):
                slack_post_followup(
                    slack, channel_id, thread_ts,
                    "I didn't recognize that. Please reply with `approve`, `reject`, or `regenerate: <feedback>`.",
                )
                d["nudged"] = True
                changed = True

    if changed:
        state.state_set("drafts", drafts)


def maybe_generate_daily_draft(
    state: SheetClient,
    slack: WebClient,
    anthropic_client: Anthropic,
    channel_id: str,
):
    """If today hasn't been drafted yet AND it's past the daily-draft hour, draft now."""
    now = now_local()
    today_str = now.strftime("%Y-%m-%d")
    last_drafted_date = state.state_get("last_drafted_date", "")
    if last_drafted_date == today_str:
        return  # already drafted today

    daily_hour = int(env("DAILY_DRAFT_HOUR", "10"))
    if now.hour < daily_hour:
        return  # too early

    LOG.info("Generating daily draft for %s", today_str)

    pending = state.fetch_pending_rows()
    drafts: list[dict] = state.state_get("drafts", [])
    in_flight_snos = {d["sno"] for d in drafts if d.get("status") in ("drafted", "posted")}

    # Pick first pending row whose SNo is not already in flight
    pick = None
    for row in pending:
        if row["sno"] and row["sno"] not in in_flight_snos:
            pick = row
            break

    if pick:
        LOG.info("Picked SNo. %s — Topic: %s", pick["sno"], pick["topic"][:60])
        req = DraftRequest(
            topic=pick["topic"],
            angle=pick["angle"],
            key_points=pick["key_points"],
            voice=pick["voice"] or "thoughtful",
            hook_style=pick["hook_style"],
            link=pick["link"],
            cta=pick["cta"],
        )
        draft_text = generate_draft(anthropic_client, req)
        thread_ts = slack_post_draft(slack, channel_id, pick["sno"], draft_text)
        drafts.append({
            "sno": pick["sno"],
            "row_number": pick["row_number"],
            "thread_ts": thread_ts,
            "draft": draft_text,
            "topic": pick["topic"],
            "angle": pick["angle"],
            "key_points": pick["key_points"],
            "voice": pick["voice"],
            "hook_style": pick["hook_style"],
            "link": pick["link"],
            "cta": pick["cta"],
            "status": "drafted",
            "drafted_at": now.isoformat(),
            "is_auto": False,
        })
        state.update_row(pick["row_number"], {"status": "drafted"})

    else:
        LOG.info("No pending rows. Falling back to AI-trend mode.")
        theme = pick_trend_theme(state)
        req = DraftRequest(
            topic=theme,
            angle="",
            voice="thoughtful",
        )
        draft_text = generate_draft(anthropic_client, req)
        # Append auto row to the queue so the user has visibility
        auto_sno = f"auto-{today_str}"
        try:
            row_number = state.append_auto_row(
                sno=auto_sno,
                topic=theme,
                voice="thoughtful",
                status="drafted",
            )
        except Exception:
            LOG.exception("Could not append auto row to queue")
            row_number = 0
        thread_ts = slack_post_draft(slack, channel_id, auto_sno, draft_text)
        drafts.append({
            "sno": auto_sno,
            "row_number": row_number,
            "thread_ts": thread_ts,
            "draft": draft_text,
            "topic": theme,
            "angle": "",
            "key_points": "",
            "voice": "thoughtful",
            "hook_style": "",
            "link": "",
            "cta": "",
            "status": "drafted",
            "drafted_at": now.isoformat(),
            "is_auto": True,
        })

    state.state_set("drafts", drafts)
    state.state_set("last_drafted_date", today_str)
    LOG.info("Daily draft posted to Slack.")


# --------------------------------------------------------------------------- #
# Entry point                                                                 #
# --------------------------------------------------------------------------- #


def main() -> int:
    sa_json = env("GOOGLE_SERVICE_ACCOUNT_JSON", required=True)
    sheet_id = env("SHEET_ID", required=True)
    anthropic_key = env("ANTHROPIC_API_KEY", required=True)
    slack_token = env("SLACK_BOT_TOKEN", required=True)
    channel_id = env("SLACK_CHANNEL_ID", required=True)
    linkedin_token = env("LINKEDIN_TOKEN", required=True)
    dry_run = env("DRY_RUN", "0") == "1"

    LOG.info("=== linkedin_automation tick at %s ===", now_local().isoformat())
    if dry_run:
        LOG.info("DRY_RUN enabled — LinkedIn POSTs will be skipped.")

    state = SheetClient.connect(sheet_id, sa_json)
    slack = WebClient(token=slack_token)
    anthropic_client = Anthropic(api_key=anthropic_key)

    bot_user_id = slack_get_bot_user_id(slack)
    member_id = ensure_member_id(state, linkedin_token)

    # Phase 1: process replies on any pending drafts
    try:
        process_pending_drafts(
            state, slack, anthropic_client, channel_id, bot_user_id,
            linkedin_token, member_id, dry_run,
        )
    except Exception:
        LOG.exception("process_pending_drafts failed")

    # Phase 2: generate today's draft if it hasn't happened yet
    try:
        maybe_generate_daily_draft(state, slack, anthropic_client, channel_id)
    except Exception:
        LOG.exception("maybe_generate_daily_draft failed")

    LOG.info("=== tick complete ===")
    return 0


if __name__ == "__main__":
    sys.exit(main())
