"""
sheets.py — Google Sheets adapter.

Reads the queue tab + manages the hidden _state tab as a key/value store.
All API calls are wrapped with retries and a circuit breaker.
"""

from __future__ import annotations

import json
import re
from dataclasses import dataclass
from typing import Any, Optional

import gspread
from google.oauth2.service_account import Credentials

from config import (
    CANONICAL_COLUMNS,
    SHEETS_SCOPES,
    STATE_TAB_NAME,
    get_logger,
    now_iso,
    today_str,
)
from reliability import sheets_breaker, with_circuit, with_http_retries

LOG = get_logger("sheets")


def _normalize_header(s: str) -> str:
    """'Generated by (Sagar/Cowork)' -> 'generated by'."""
    s = re.sub(r"\(.*?\)", "", s).strip().lower()
    s = re.sub(r"\s+", " ", s)
    return s


def _map_columns(headers: list[str]) -> dict[str, int]:
    norm = [_normalize_header(h) for h in headers]
    out: dict[str, int] = {}
    for canonical, aliases in CANONICAL_COLUMNS.items():
        for alias in aliases:
            if alias in norm:
                out[canonical] = norm.index(alias)
                break
    return out


@dataclass
class SheetClient:
    sheet_id: str
    gc: gspread.Client
    sh: gspread.Spreadsheet
    queue_ws: gspread.Worksheet
    state_ws: gspread.Worksheet
    col_idx: dict[str, int]
    headers: list[str]

    @classmethod
    @with_circuit(sheets_breaker)
    @with_http_retries
    def connect(cls, sheet_id: str, sa_json: str) -> "SheetClient":
        creds_info = json.loads(sa_json)
        creds = Credentials.from_service_account_info(creds_info, scopes=SHEETS_SCOPES)
        gc = gspread.authorize(creds)
        sh = gc.open_by_key(sheet_id)
        queue_ws = sh.sheet1
        try:
            state_ws = sh.worksheet(STATE_TAB_NAME)
        except gspread.WorksheetNotFound:
            LOG.info("Creating %s tab (first run)", STATE_TAB_NAME)
            state_ws = sh.add_worksheet(title=STATE_TAB_NAME, rows=200, cols=2)
            state_ws.update("A1:B1", [["key", "value"]])
        headers = queue_ws.row_values(1)
        col_idx = _map_columns(headers)
        LOG.info("Mapped queue columns: %s", col_idx)
        return cls(sheet_id, gc, sh, queue_ws, state_ws, col_idx, headers)

    # ------------------------------------------------------------------ queue tab

    @with_http_retries
    def fetch_pending_rows(self) -> list[dict[str, Any]]:
        """All rows whose Status is empty or 'pending' (case-insensitive)."""
        all_rows = self.queue_ws.get_all_values()
        if len(all_rows) < 2:
            return []
        out: list[dict[str, Any]] = []
        status_col = self.col_idx.get("status")
        max_idx = max(self.col_idx.values(), default=0)
        for row_number, raw in enumerate(all_rows[1:], start=2):
            raw = raw + [""] * (max_idx + 1 - len(raw))
            status = (raw[status_col].strip().lower() if status_col is not None else "")
            if status in ("", "pending"):
                out.append(self._row_to_dict(row_number, raw))
        LOG.info("Found %d pending rows", len(out))
        return out

    @with_http_retries
    def fetch_posted_rows(self) -> list[dict[str, Any]]:
        """All rows whose Status is 'posted' AND have a post URL.
        Used by the engagement sync to refresh reach scores."""
        all_rows = self.queue_ws.get_all_values()
        if len(all_rows) < 2:
            return []
        out: list[dict[str, Any]] = []
        status_col = self.col_idx.get("status")
        post_url_col = self.col_idx.get("post_url")
        max_idx = max(self.col_idx.values(), default=0)
        for row_number, raw in enumerate(all_rows[1:], start=2):
            raw = raw + [""] * (max_idx + 1 - len(raw))
            status = (raw[status_col].strip().lower() if status_col is not None else "")
            post_url = (raw[post_url_col].strip() if post_url_col is not None else "")
            if status == "posted" and post_url:
                out.append(self._row_to_dict(row_number, raw))
        LOG.info("Found %d posted rows with URLs", len(out))
        return out

    def _row_to_dict(self, row_number: int, raw: list[str]) -> dict[str, Any]:
        return {
            "row_number": row_number,
            "raw": raw,
            "sno": self._cell(raw, "sno"),
            "date": self._cell(raw, "date"),
            "topic": self._cell(raw, "topic"),
            "angle": self._cell(raw, "angle"),
            "key_points": self._cell(raw, "key_points"),
            "voice": self._cell(raw, "voice"),
            "hook_style": self._cell(raw, "hook_style"),
            "link": self._cell(raw, "link"),
            "cta": self._cell(raw, "cta"),
            "status": self._cell(raw, "status"),
            "post_url": self._cell(raw, "post_url"),
            "reach_score": self._cell(raw, "reach_score"),
            "notes": self._cell(raw, "notes"),
            "generated_by": self._cell(raw, "generated_by"),
        }

    def _cell(self, row: list[str], key: str) -> str:
        idx = self.col_idx.get(key)
        if idx is None or idx >= len(row):
            return ""
        return str(row[idx]).strip()

    @with_http_retries
    def update_row(self, row_number: int, updates: dict[str, str]) -> None:
        for key, value in updates.items():
            idx = self.col_idx.get(key)
            if idx is None:
                LOG.warning("No column mapped for '%s', skipping write", key)
                continue
            col_letter = gspread.utils.rowcol_to_a1(1, idx + 1).rstrip("1")
            cell = f"{col_letter}{row_number}"
            self.queue_ws.update(cell, [[value]])
            LOG.info("Wrote row=%s %s=%r", row_number, key, str(value)[:60])

    @with_http_retries
    def append_to_notes(self, row_number: int, note_line: str) -> None:
        idx = self.col_idx.get("notes")
        if idx is None:
            LOG.warning("No 'notes' column mapped — skipping note append")
            return
        col_letter = gspread.utils.rowcol_to_a1(1, idx + 1).rstrip("1")
        cell = f"{col_letter}{row_number}"
        existing = self.queue_ws.acell(cell).value or ""
        timestamped = f"[{now_iso()}] {note_line}"
        new_value = (existing + "\n" + timestamped).strip()
        self.queue_ws.update(cell, [[new_value]])
        LOG.info("Appended note on row=%s: %s", row_number, note_line[:80])

    @with_http_retries
    def append_auto_row(
        self,
        sno: str,
        topic: str,
        angle: str = "",
        voice: str = "thoughtful",
        status: str = "pending",
    ) -> int:
        new_row = [""] * len(self.headers)
        fields = {
            "sno": sno,
            "date": today_str(),
            "topic": topic,
            "angle": angle,
            "voice": voice,
            "status": status,
            "generated_by": "Cowork",
        }
        for key, value in fields.items():
            idx = self.col_idx.get(key)
            if idx is not None and idx < len(new_row):
                new_row[idx] = value
        self.queue_ws.append_row(new_row, value_input_option="USER_ENTERED")
        all_rows = self.queue_ws.get_all_values()
        row_number = len(all_rows)
        LOG.info("Appended auto-row at row=%s sno=%s topic=%r", row_number, sno, topic[:60])
        return row_number

    # ----------------------------------------------------------- state tab (key/value)

    @with_http_retries
    def state_get(self, key: str, default: Any = None) -> Any:
        rows = self.state_ws.get_all_values()
        for r in rows[1:]:
            if r and r[0] == key:
                if len(r) >= 2 and r[1]:
                    try:
                        return json.loads(r[1])
                    except json.JSONDecodeError:
                        return r[1]
                return default
        return default

    @with_http_retries
    def state_set(self, key: str, value: Any) -> None:
        rows = self.state_ws.get_all_values()
        serialized = json.dumps(value) if not isinstance(value, str) else value
        for i, r in enumerate(rows[1:], start=2):
            if r and r[0] == key:
                self.state_ws.update(f"B{i}", [[serialized]])
                return
        self.state_ws.append_row([key, serialized], value_input_option="RAW")
