"""Tests for pure parsing logic — header normalization, critic output, URL extraction."""

from generator import parse_critic_output
from linkedin_api import extract_urn_from_post_url
from sheets import _map_columns, _normalize_header


class TestNormalizeHeader:
    def test_strips_parens(self):
        assert _normalize_header("Generated by (Sagar/Cowork)") == "generated by"

    def test_lowercase(self):
        assert _normalize_header("Topic") == "topic"

    def test_collapses_whitespace(self):
        assert _normalize_header("Key   Points") == "key points"

    def test_trims(self):
        assert _normalize_header("  Date  ") == "date"


class TestMapColumns:
    def test_finds_canonical_columns(self):
        headers = ["SNo.", "Date", "Topic", "Status"]
        idx = _map_columns(headers)
        assert idx["sno"] == 0
        assert idx["date"] == 1
        assert idx["topic"] == 2
        assert idx["status"] == 3

    def test_handles_aliases(self):
        headers = ["#", "Topic", "Tone"]  # # for sno, Tone for voice
        idx = _map_columns(headers)
        assert idx["sno"] == 0
        assert idx["voice"] == 2

    def test_unmapped_columns_excluded(self):
        headers = ["Topic", "Random Column", "Status"]
        idx = _map_columns(headers)
        assert "topic" in idx
        assert "status" in idx
        assert len(idx) == 2  # random column not mapped


class TestParseCriticOutput:
    def test_pass_verdict(self):
        text = "HOOK: 5\nVERDICT: PASS\nREVISION_NOTES:"
        out = parse_critic_output(text)
        assert out["verdict"] == "PASS"
        assert out["notes"] == ""

    def test_revise_with_notes(self):
        text = """HOOK: 3
CLARITY: 4
VERDICT: REVISE
REVISION_NOTES: Tighten the second paragraph. Cut the example about Bob."""
        out = parse_critic_output(text)
        assert out["verdict"] == "REVISE"
        assert "Tighten" in out["notes"]
        assert "Cut the example" in out["notes"]

    def test_fail_verdict(self):
        text = "VERDICT: FAIL\nREVISION_NOTES: Off topic."
        out = parse_critic_output(text)
        assert out["verdict"] == "FAIL"

    def test_multiline_notes_concatenated(self):
        text = """VERDICT: REVISE
REVISION_NOTES: First sentence.
Second sentence."""
        out = parse_critic_output(text)
        assert "First sentence" in out["notes"]
        assert "Second sentence" in out["notes"]


class TestExtractUrn:
    def test_extracts_share_urn(self):
        url = "https://www.linkedin.com/feed/update/urn:li:share:7457025367162134528/"
        assert extract_urn_from_post_url(url) == "urn:li:share:7457025367162134528"

    def test_extracts_ugc_urn(self):
        url = "https://www.linkedin.com/feed/update/urn:li:ugcPost:7193456789/"
        assert extract_urn_from_post_url(url) == "urn:li:ugcPost:7193456789"

    def test_returns_none_for_non_linkedin_url(self):
        assert extract_urn_from_post_url("https://example.com/post") is None

    def test_returns_none_for_empty(self):
        assert extract_urn_from_post_url("") is None

    def test_handles_trailing_query_string(self):
        url = "https://www.linkedin.com/feed/update/urn:li:share:7193?ref=feed"
        assert extract_urn_from_post_url(url) == "urn:li:share:7193"
